name: EAS Build and Deploy

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/mobile/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/mobile/**'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ios
          - android
      profile:
        description: 'Build profile'
        required: true
        default: 'preview'
        type: choice
        options:
          - development
          - preview
          - production

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}

jobs:
  build:
    name: Build on EAS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ios, android]
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: apps/mobile/package-lock.json

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        working-directory: apps/mobile
        run: npm ci

      - name: 🔍 Verify TypeScript
        working-directory: apps/mobile
        run: npm run type-check

      - name: 🧹 Lint code
        working-directory: apps/mobile
        run: npm run lint

      - name: 📱 Build on EAS
        working-directory: apps/mobile
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            PLATFORM="${{ github.event.inputs.platform }}"
            PROFILE="${{ github.event.inputs.profile }}"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            PLATFORM="${{ matrix.platform }}"
            PROFILE="production"
          else
            PLATFORM="${{ matrix.platform }}"
            PROFILE="preview"
          fi

          if [[ "$PLATFORM" == "all" ]]; then
            eas build --platform all --profile $PROFILE --non-interactive
          else
            eas build --platform $PLATFORM --profile $PROFILE --non-interactive
          fi

  submit-production:
    name: Submit to App Stores
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        platform: [ios, android]
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: apps/mobile/package-lock.json

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        working-directory: apps/mobile
        run: npm ci

      - name: 🚀 Submit to ${{ matrix.platform }}
        working-directory: apps/mobile
        run: eas submit --platform ${{ matrix.platform }} --latest --non-interactive

  notify:
    name: Notify Build Status
    runs-on: ubuntu-latest
    needs: [build, submit-production]
    if: always()
    steps:
      - name: 📢 Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#mobile-builds'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}