name: EAS Update

on:
  push:
    branches: [develop, staging]
    paths:
      - 'apps/mobile/**'
      - '!apps/mobile/android/**'
      - '!apps/mobile/ios/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy update'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - staging
          - main

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: apps/mobile/package-lock.json

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        working-directory: apps/mobile
        run: npm ci

      - name: 🔍 Verify TypeScript
        working-directory: apps/mobile
        run: npm run type-check

      - name: 🧹 Lint code
        working-directory: apps/mobile
        run: npm run lint

      - name: 📄 Determine update branch
        working-directory: apps/mobile
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            BRANCH="${{ github.event.inputs.branch }}"
          else
            BRANCH="${{ github.ref_name }}"
          fi
          echo "UPDATE_BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: 🚀 Publish update
        working-directory: apps/mobile
        run: |
          eas update --branch ${{ env.UPDATE_BRANCH }} --message "Update from ${{ github.sha }}" --non-interactive

      - name: 📢 Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#mobile-updates'
          text: |
            EAS Update published to branch: ${{ env.UPDATE_BRANCH }}
            Commit: ${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}