name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run type-check
      - name: Unit / Integration tests (with coverage)
        run: npm test -- --runInBand --coverage
      - name: Build (static analysis)
        run: npm run build
      - name: Install Playwright browsers
        run: pnpx playwright install --with-deps
      - name: E2E tests
        run: pnpx playwright test --reporter="dot,html"
      - name: Generate sitemap
        run: npm run next-sitemap
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report 